# cloudbuild.yaml - Para CI/CD automático
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/pnp-bot:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/pnp-bot:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pnp-bot:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pnp-bot:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'pnp-bot',
      '--image', 'gcr.io/$PROJECT_ID/pnp-bot:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '1',
      '--max-instances', '3'
    ]

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s